version: '3.9'
services:
    flask_app:
        build: ./app
        ports:
        - 5000:80
        command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
    nginx:
        build: ./nginx
        ports:
        - 8080:80
        depends_on:
        - flask_app